### ISSUE TITLE
crenv install error

### ISSUE THREAD

**Issue by tebakane** [pine/crenv#11]
今回crenvを使用させていただきました。
その際問題が発生しました。
どの様に解決すべきか教えていただけると助かります。

crenv install 0.9.0 を行った際(0.8.0でも発生しました)下記のエラーが発生しました。

```
Can't locate version.pm in @INC (@INC contains: /home/test/.crenv/plugins/crystal-build/bin/../vendor/lib /home/test/.crenv/plugins/crystal-build/bin/../lib /usr/local/lib64/»  3 BEGIN failed--compilation aborted at /home/test/.crenv/plugins/crystal-build/bin/../vendor/lib/SemVer.pm line 5.↲
Compilation failed in require at /home/test/.crenv/plugins/crystal-build/bin/../lib/Crenv.pm line 10.↲
BEGIN failed--compilation aborted at /home/test/.crenv/plugins/crystal-build/bin/../lib/Crenv.pm line 10.↲
Compilation failed in require at /home/test/.crenv/plugins/crystal-build/bin/crystal-build line 15.↲
BEGIN failed--compilation aborted at /home/test/.crenv/plugins/crystal-build/bin/crystal-build line 15.↲
If the version you're looking for is not present, first try upgrading↲
crystal-build. If it's still missing, open a request on the crystal-build↲
issue tracker: https://github.com/pine613/crystal-build/issues↲
```

現在、SemVer.pmファイルの5行目をコメントアウトすることで対応しています。

SemVer.pmのファイルは下記の様に記載されています。

```
package SemVer;↲

use 5.008001;↲
use strict;↲
use version 0.77;↲
use Scalar::Util ();↲
```

use version 0.77の箇所をコメントアウトして動作はしているのですが
どのように対処するのが最適か教えていただけますか。
Perlは初心者のためわからないことが多いのですがよろしくお願いします。

使用環境

```
CentOS Linux release 7.1.1503 (Core) 
```

Perl

```
perl --version

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 28 registered patches, see perl -V for more detail)
```

よろしくお願いします。

**Comment by pine** [comment]
バグ報告ありがとうございます。
早急に調査、修正いたします…。

**Comment by tebakane** [comment]
必要な情報がありましたら
おっしゃってください。

**Comment by pine** [comment]
@tebakane 
報告していただいたバグを修正しました。
この問題は Cent OS に入っている Perl の標準モジュールが欠けていることに起因するものです。
http://d.hatena.ne.jp/perlcodesample/20120603/1339333786

crenv (正しく言うと [crystal-build](https://github.com/pine613/crystal-build)) で参照していた version モジュールは Perl v5.9.0 以降の標準モジュールなのですが、Cent OS 標準の Perl にはそれが入っていませんでした。

特に複雑な処理を依存していたわけではないので、そのライブラリに依存していた部分を別途実装して対応しました。
https://github.com/pine613/crystal-build/pull/27/files

現在の最新版では、この問題は修正されています。
更新するには、以下のコマンドを実行してください。

```
$ cd ~/.crenv/plugins/crystal-build
$ git pull origin master
$ exec $SHELL -l
```

このたびはバグの報告ありがとうございました。

**Comment by tebakane** [comment]
対応ありがとうございます。
