### ISSUE TITLE
Get crystal version from shard.yml

### ISSUE THREAD

**Issue by spalladino** [pine/crenv#27]
Since commit https://github.com/crystal-lang/crystal/commit/6b09c3b0f5c485ed3d179274026fbc54d1c48b21, `crystal init` adds the crystal version to the project `shard.yml`. What do you think about attempting to retrieve the version from that file if no `.crystal-version` file is present in the project root?

The main problem for doing that would be parsing the YAML file. To do that, we could:
- Take advantage of the fact that the crystal version is at the top of the YAML document, and use `sed` to extract it
- Check if ruby (or another scripting language) is available, and use it to parse the file and extract the value; though this would make crenv's behaviour heavily dependent on the platform

I'd go with the first option, even if using a regex to parse a YAML file gives me the chills.

**Comment by pine** [comment]
It's very very good idea!! Thanks!

**Comment by pine** [comment]
In the most ideal state, `shards` has sub command (like `shards crystal-version`), and  it returns crystal version. But now, we should parse YAML file by shell scripts or other tools 😔

**Comment by pine** [comment]
First, I'll try to parse YAML file by bash shell script. Next, I'll search other languages (Perl, Python, Ruby, etc...).

**Comment by spalladino** [comment]
> It's very very good idea!! Thanks!

Actually, it was @asterite's idea, after I asked him what he thought about adding a `.crystal-version` to the `crystal init` template. He suggested this to avoid duplication with the shard file. So, thanks for considering this!!

As for the shards subcommand, we can always send a PR; that might be easier than actually parsing YAML in bash.

**Comment by pine** [comment]
@spalladino I'm developing for this issue, so please wait for a few days.

**Comment by pine** [comment]
@spalladino I've just merged shard.yml supports #29. Thank you.

**Comment by spalladino** [comment]
Awesome, thanks a lot @pine!!
