### ISSUE TITLE
version not found (crystal-build?)

### ISSUE THREAD

**Issue by mihyaeru21** [pine/crenv#3]
I got this output.

on Mac OSX 10.10

```
$ crenv install - l
resolve: crystal---darwin-x64
version not found
```

on Ubuntu 12.04

```
$ crenv install -l
resolve: crystal--l-linux-x64
version not found
```

**Comment by pine** [comment]
`crystal-build` has not supported `-l` option yet.

Please try this commands as following:

```
$ crenv install 0.7.4
```

Thank you.

**Comment by mattak** [comment]
:+1:

**Comment by pine** [comment]
OK.
I've opened new issues in [crysta-build](https://github.com/pine613/crystal-build) repository.

Thanks.

**Comment by pine** [comment]
I fixed it. Enjoy!
