### ISSUE TITLE
not found version

### ISSUE THREAD

**Issue by denovez** [pine/crenv#31]
please help what this wrong, i cant found all version of crystal.

`agun:~ $ crenv -v`
`crenv 1.1.0`
`agun:~ $ crenv install 0.20.0`
`Resolving Crystal download URL by Remote Cache ... ng`
`Resolving Crystal download URL by GitHub ... ng`
`Error: Version not found`
`agun:~ $`

**Comment by pine** [comment]
@denovez  Thanks reports. Which OS do you use now ?

**Comment by denovez** [comment]
Thanks for reply,
I use mac os 10.6.8 32bit, it posible installing there?

**Comment by pine** [comment]
@denovez Sorry. crenv does not support 32 bit of macOS, because official Crystal binary is not provided for 32 bit macOS :pensive:

**Comment by pine** [comment]
Try to use another computers, another OS, or Linux VMs. Thank you.

**Comment by kubo39** [comment]
@pine This is not a crenv's bug, so close it.

**Comment by pine** [comment]
OK, Thanks!
