### ISSUE TITLE
error install crystal 0.21.0 - something related to libevent

### ISSUE THREAD

**Issue by fridgerator** [pine/crenv#33]
Mac Sierra (10.12.3)
zsh 5.2

http://pastebin.com/qWXGQbPx

**Comment by pine** [comment]
Hello @fridgerator. I try to fix it.

- https://github.com/pine/crystal-build/commit/6e96465f1d446b585e954b9d2f917bdec3d4575a
- https://github.com/pine/crystal-build/commit/2714f734e0ddd1c45b02885e5fd82d51fdac79cb

Please update crystal-build and retry.

```
$ cd $(crenv root)/plugins/crystal-build
$ git pull origin master

$ cd
$ crenv install 0.21.0
```

Thank you.

**Comment by fridgerator** [comment]
that worked, thanks!
